(function () {
  "use strict";

  window.YARN_CATALOG = [
    { brand: "Berroco", name: "Vintage", weight: "Worsted", yards: 218, grams: 100, knitGauge: [18, 20], crochetGauge: [15, 16], fiber: "Wool blend", sourceUrl: "https://berroco.com/yarns/vintage/" },
    { brand: "Cascade Yarns", name: "Cascade 220", weight: "Worsted", yards: 220, grams: 100, knitGauge: [18, 20], crochetGauge: null, fiber: "100% wool", sourceUrl: "https://www.cascadeyarns.com/product/cascade-220" },
    { brand: "Jody Long", name: "Ciao", weight: "DK", yards: 115, grams: 50, knitGauge: [21, 24], crochetGauge: [12, 17], fiber: "100% superwash merino", sourceUrl: "https://jodylongyarn.com/yarn/E-CIAO" },
    { brand: "Kelbourne Woolens", name: "Germantown", weight: "Worsted", yards: 220, grams: 100, knitGauge: [16, 20], crochetGauge: null, fiber: "100% wool", sourceUrl: "https://kelbournewoolens.com/products/kelbourne-woolens-germantown" },
    { brand: "Koigu", name: "KPPPM", weight: "Fingering", yards: 170, grams: 50, knitGauge: [28, 28], crochetGauge: null, fiber: "100% merino wool", sourceUrl: "https://www.koigu.com/kpppm/" },
    { brand: "Lion Brand", name: "24/7 Cotton", weight: "Worsted", yards: 185, grams: 100, knitGauge: [20, 20], crochetGauge: [14, 14], fiber: "100% cotton", sourceUrl: "https://www.lionbrand.com/collections/cotton-knitting-crochet-yarn/products/24-7-cotton" },
    { brand: "Lion Brand", name: "Heartland", weight: "Worsted", yards: 251, grams: 142, knitGauge: [16, 16], crochetGauge: [12, 12], fiber: "Acrylic", sourceUrl: "https://www.lionbrand.com/collections/yarn-weight-4-medium/products/heartland-yarn" },
    { brand: "Lopi", name: "Léttlopi", weight: "Aran", yards: 109, grams: 50, knitGauge: [18, 18], crochetGauge: null, fiber: "100% Icelandic wool", sourceUrl: "https://istex.is/en/vorur/lettlopi/" },
    { brand: "Malabrigo", name: "Rios", weight: "Worsted", yards: 210, grams: 100, knitGauge: [18, 22], crochetGauge: null, fiber: "100% superwash merino", sourceUrl: "https://malabrigoyarn.com/yarns/rios" },
    { brand: "Plymouth Yarn", name: "Encore Worsted", weight: "Worsted", yards: 200, grams: 100, knitGauge: [20, 20], crochetGauge: null, fiber: "75% acrylic / 25% wool", sourceUrl: "https://www.plymouthyarn.com/yarn/encore-worsted-item-611" },
    { brand: "Queensland Collection", name: "Coastal Cotton", weight: "Worsted", yards: 185, grams: 100, knitGauge: [16, 20], crochetGauge: [11, 11], fiber: "100% cotton", sourceUrl: "https://queenslandcollectionyarn.com/yarn/E-COASCOT" },

    { brand: "Knit Picks", name: "Brava Baby DK", weight: "DK", yards: 273, grams: 100, knitGauge: [22, 22], crochetGauge: [12, 17], fiber: "100% premium anti-pill acrylic", sourceUrl: "https://www.knitpicks.com/rose/p/N7673" },
    { brand: "Knit Picks", name: "Brava Sport", weight: "Sport", yards: 340, grams: 100, knitGauge: [24, 24], crochetGauge: [16, 20], fiber: "100% premium acrylic", sourceUrl: "https://www.knitpicks.com/tidepool/p/28404" },
    { brand: "Knit Picks", name: "Brava Worsted", weight: "Worsted", yards: 218, grams: 100, knitGauge: null, crochetGauge: null, fiber: "100% premium acrylic", sourceUrl: "https://blog.knitpicks.com/brava/" },
    { brand: "Knit Picks", name: "Capra DK", weight: "DK", yards: 123, grams: 50, knitGauge: [20, 22], crochetGauge: [12, 17], fiber: "85% merino / 15% cashmere", sourceUrl: "https://www.knitpicks.com/angelite-heather/p/27665" },
    { brand: "Knit Picks", name: "Chroma Worsted", weight: "Worsted", yards: 198, grams: 100, knitGauge: [18, 20], crochetGauge: [11, 14], fiber: "70% superwash wool / 30% nylon", sourceUrl: "https://www.knitpicks.com/beatrix/p/N2175" },
    { brand: "Knit Picks", name: "Comfy Worsted", weight: "Worsted", yards: 109, grams: 50, knitGauge: [18, 20], crochetGauge: [11, 14], fiber: "75% Pima cotton / 25% acrylic", sourceUrl: "https://www.knitpicks.com/hawk/p/25312" },
    { brand: "Knit Picks", name: "CotLin", weight: "DK", yards: 123, grams: 50, knitGauge: [22, 22], crochetGauge: [12, 17], fiber: "70% cotton / 30% linen", sourceUrl: "https://blog.knitpicks.com/a-guide-to-knit-picks-cotton-yarns/" },
    { brand: "Knit Picks", name: "Dishie", weight: "Worsted", yards: 190, grams: 100, knitGauge: [18, 18], crochetGauge: [11, 14], fiber: "100% cotton", sourceUrl: "https://blog.knitpicks.com/choosing-the-right-cotton-yarn-for-your-projects/" },
    { brand: "Knit Picks", name: "Fluff of the Andes", weight: "Super Bulky", yards: 109, grams: 200, knitGauge: [10, 10], crochetGauge: [9, 9], fiber: "100% Highland wool", sourceUrl: "https://www.knitpicks.com/baltic-heather/p/61280" },
    { brand: "Knit Picks", name: "Hawthorne Fingering", weight: "Fingering", yards: 357, grams: 100, knitGauge: [28, 32], crochetGauge: [21, 23], fiber: "80% superwash wool / 20% nylon", sourceUrl: "https://www.knitpicks.com/slabtown-multi/p/27837" },
    { brand: "Knit Picks", name: "High Desert Sport", weight: "Sport", yards: 298, grams: 100, knitGauge: [24, 24], crochetGauge: [16, 20], fiber: "100% American wool", sourceUrl: "https://www.knitpicks.com/yarn/high-desert-sport-yarn/c/5420426" },
    { brand: "Knit Picks", name: "High Desert Worsted", weight: "Worsted", yards: 217, grams: 100, knitGauge: [18, 20], crochetGauge: [11, 14], fiber: "100% American wool", sourceUrl: "https://www.knitpicks.com/campion/p/N5424" },
    { brand: "Knit Picks", name: "Palette", weight: "Fingering", yards: 231, grams: 50, knitGauge: [28, 32], crochetGauge: [21, 23], fiber: "100% Peruvian Highland wool", sourceUrl: "https://www.knitpicks.com/yarn/palette-yarn/c/5420132" },
    { brand: "Knit Picks", name: "Simply Alpaca", weight: "Aran", yards: 246, grams: 100, knitGauge: null, crochetGauge: null, fiber: "100% superfine alpaca", sourceUrl: "https://blog.knitpicks.com/our-new-yarns-november-2017/" },
    { brand: "Knit Picks", name: "Simply Wool Aran", weight: "Aran", yards: 193, grams: 100, knitGauge: [12, 15], crochetGauge: [8, 11], fiber: "100% eco wool", sourceUrl: "https://www.knitpicks.com/yarn/simply-wool-aran-yarn/c/5420318" },
    { brand: "Knit Picks", name: "Stroll", weight: "Fingering", yards: 231, grams: 50, knitGauge: [28, 32], crochetGauge: [21, 23], fiber: "75% superwash merino / 25% nylon", sourceUrl: "https://blog.knitpicks.com/guide-to-knit-picks-sock-yarns/" },
    { brand: "Knit Picks", name: "Stroll Effects (Hand Painted / Tonal)", weight: "Fingering", yards: 462, grams: 100, knitGauge: [28, 32], crochetGauge: [21, 23], fiber: "75% superwash merino / 25% nylon", sourceUrl: "https://www.knitpicks.com/spring-meadow-hand-paint/p/N4364" },
    { brand: "Knit Picks", name: "Swish Worsted", weight: "Worsted", yards: 110, grams: 50, knitGauge: [18, 20], crochetGauge: [11, 14], fiber: "100% superwash merino", sourceUrl: "https://www.knitpicks.com/poet/p/N4132" },
    { brand: "Knit Picks", name: "Wonderfluff", weight: "Bulky", yards: 142, grams: 50, knitGauge: null, crochetGauge: null, fiber: "Alpaca / merino / nylon blown yarn", sourceUrl: "https://blog.knitpicks.com/introducing-wonderfluff/" },
    { brand: "Knit Picks", name: "Wool of the Andes Sport", weight: "Sport", yards: 137, grams: 50, knitGauge: [24, 24], crochetGauge: [16, 20], fiber: "100% Peruvian Highland wool", sourceUrl: "https://www.knitpicks.com/mink-heather/p/25275" },
    { brand: "Knit Picks", name: "Wool of the Andes Superwash Worsted", weight: "Worsted", yards: 110, grams: 50, knitGauge: [18, 20], crochetGauge: [11, 14], fiber: "100% superwash wool", sourceUrl: "https://www.knitpicks.com/yarn/wool-of-the-andes-superwash-worsted-yarn/c/5420246" },
    { brand: "Knit Picks", name: "Wool of the Andes Tweed Worsted", weight: "Worsted", yards: 110, grams: 50, knitGauge: [18, 20], crochetGauge: [11, 14], fiber: "80% wool / 20% Donegal tweed", sourceUrl: "https://www.knitpicks.com/square-dance-heather/p/28303" },
    { brand: "Knit Picks", name: "Wool of the Andes Worsted", weight: "Worsted", yards: 110, grams: 50, knitGauge: [18, 20], crochetGauge: [11, 14], fiber: "100% Peruvian Highland wool", sourceUrl: "https://www.knitpicks.com/delft-heather/p/25649" },
    { brand: "Knit Picks", name: "Yakish", weight: "Sport", yards: 123, grams: 50, knitGauge: [22, 24], crochetGauge: [16, 21], fiber: "Alpaca / merino / yak", sourceUrl: "https://blog.knitpicks.com/introducing-yakish-a-knit-picks-yarn/" }
  ];

  window.PATTERN_CATALOG = [
    { name: "Crown", image: "https://cdn11.bigcommerce.com/s-x11gxbo1oj/images/stencil/640w/products/8268/18489/Crown-1__90520.1721069725.jpg?c=1", designer: "Åsa Buchta", craft: "knit", project: "Hat", weight: "Worsted", minYards: 150, maxYards: 218, gauge: 20, url: "https://berroco.com/patterns/crown/", free: true, usedYarns: ["Berroco|Vintage"], sourceBrand: "Berroco" },
    { name: "Echelon", image: "https://cdn11.bigcommerce.com/s-x11gxbo1oj/images/stencil/640w/products/4237/9321/echelon_lg__24924.1721053442.jpg?c=1", designer: "Shelby Allaho", craft: "crochet", project: "Hat", weight: "Worsted", minYards: 160, maxYards: 218, gauge: 20, url: "https://berroco.com/patterns/echelon/", free: true, sourceBrand: "Berroco" },
    { name: "Alison's Basic Hat Recipe", image: "https://cdn11.bigcommerce.com/s-x11gxbo1oj/images/stencil/640w/products/8474/19067/AlisonHatRecipe-3__49384.1723819204.jpg?c=1", designer: "Alison Green", craft: "knit", project: "Hat", weight: "Any", minYards: 100, maxYards: 300, gauge: null, url: "https://berroco.com/patterns/alisons-basic-hat-recipe/", free: true, sourceBrand: "Berroco" },
    { name: "Textures Hat", image: "https://www.lionbrand.com/cdn/shop/files/M25114.HL-M25113.HL-0487_Shopify_800x.jpg?v=1764009233", designer: "Lion Brand", craft: "knit", project: "Hat", weight: "Worsted", minYards: 170, maxYards: 251, gauge: 16, url: "https://www.lionbrand.com/products/textures-hat-knit", free: true, usedYarns: ["Lion Brand|Heartland"], sourceBrand: "Lion Brand" },
    { name: "April Hat", designer: "Kelbourne Woolens", craft: "knit", project: "Hat", weight: "Worsted", minYards: 180, maxYards: 220, gauge: null, url: "https://kelbournewoolens.com/products/april-hat-free-pattern", free: true, usedYarns: ["Kelbourne Woolens|Germantown"], sourceBrand: "Kelbourne Woolens" },
    { name: "March Hat", designer: "Kelbourne Woolens", craft: "knit", project: "Hat", weight: "Worsted", minYards: 180, maxYards: 220, gauge: null, url: "https://kelbournewoolens.com/products/march-hat-free-pattern", free: true, usedYarns: ["Kelbourne Woolens|Germantown"], sourceBrand: "Kelbourne Woolens" },
    { name: "Encore Worsted Pullover 2576", image: "https://www.plymouthyarn.com/sites/default/files/Encore%20Worsted%202576.jpg", designer: "Plymouth Yarn", craft: "knit", project: "Sweater", weight: "Worsted", minYards: 800, maxYards: 1200, gauge: 18, url: "https://www.plymouthyarn.com/pattern/encore-worsted-171", free: false, usedYarns: ["Plymouth Yarn|Encore Worsted"], sourceBrand: "Plymouth Yarn" },
    { name: "Encore Worsted Cardigan 114A", image: "https://www.plymouthyarn.com/sites/default/files/Encore%20Worsted%20114A.jpg", designer: "Plymouth Yarn", craft: "knit", project: "Sweater", weight: "Worsted", minYards: 1000, maxYards: 1400, gauge: 16.5, url: "https://www.plymouthyarn.com/pattern/encore-worsted-134", free: false, usedYarns: ["Plymouth Yarn|Encore Worsted"], sourceBrand: "Plymouth Yarn" },
    { name: "Cascade Christmas Stocking", designer: "Marji LaFreniere", craft: "knit", project: "Stocking", weight: "Worsted", minYards: 220, maxYards: 440, gauge: 18, url: "https://www.cascadeyarns.com/wp-content/uploads/2022/07/W104_220.pdf", free: true, usedYarns: ["Cascade Yarns|Cascade 220"], sourceBrand: "Cascade Yarns" },

    { name: "Rosalie", designer: "Jody Long", craft: "knit", project: "Sweater", weight: "DK", minYards: 1495, maxYards: 2415, gauge: 22, url: "https://knittingfever.com/design/21837", free: false, usedYarns: ["Jody Long|Ciao"], sourceBrand: "Jody Long" },
    { name: "Sorrento", designer: "Jody Long", craft: "knit", project: "Sweater", weight: "DK", minYards: 1495, maxYards: 2645, gauge: 22, url: "https://knittingfever.com/design/20669", free: false, usedYarns: ["Jody Long|Ciao"], sourceBrand: "Jody Long" },
    { name: "Francisco", designer: "Jody Long", craft: "knit", project: "Baby", weight: "DK", minYards: 575, maxYards: 1035, gauge: 22, url: "https://knittingfever.com/design/20361", free: false, usedYarns: ["Jody Long|Ciao"], sourceBrand: "Jody Long" },
    { name: "Lorenzo", designer: "Jody Long", craft: "knit", project: "Baby", weight: "DK", minYards: 345, maxYards: 575, gauge: 22, url: "https://knittingfever.com/design/18158", free: false, usedYarns: ["Jody Long|Ciao"], sourceBrand: "Jody Long" },

    { name: "Offset Rib Cowl", image: "https://images4-f.ravelrycache.com/uploads/Simone77/307687191/55700220crop_small.jpg", designer: "Simone Kereit", craft: "knit", project: "Cowl", weight: "DK", minYards: 246, maxYards: 492, gauge: null, url: "https://blog.knitpicks.com/free-patterns-capra/", free: true, usedYarns: ["Knit Picks|Capra DK"], sourceBrand: "Knit Picks" },
    { name: "Simple Shells Beanie", designer: "Beth Major", craft: "crochet", project: "Hat", weight: "DK", minYards: 123, maxYards: 246, gauge: null, url: "https://blog.knitpicks.com/free-patterns-capra/", free: true, usedYarns: ["Knit Picks|Capra DK"], sourceBrand: "Knit Picks" },
    { name: "Basic Mittens", designer: "Knit Picks", craft: "knit", project: "Mittens", weight: "Worsted", minYards: 110, maxYards: 330, gauge: null, url: "https://www.knitpicks.com/delft-heather/p/25649", free: false, usedYarns: ["Knit Picks|Wool of the Andes Worsted", "Knit Picks|Wool of the Andes Superwash Worsted"], sourceBrand: "Knit Picks" },
    { name: "Keighley Hat & Scarf", designer: "Knit Picks", craft: "knit", project: "Scarf", weight: "Worsted", minYards: 330, maxYards: 660, gauge: null, url: "https://www.knitpicks.com/delft-heather/p/25649", free: true, usedYarns: ["Knit Picks|Wool of the Andes Worsted"], sourceBrand: "Knit Picks" },
    { name: "Ribbed Watch Cap", image: "https://images4-f.ravelrycache.com/uploads/KPStaff/890129930/upload_small2", designer: "Knit Picks", craft: "knit", project: "Hat", weight: "Worsted", minYards: 110, maxYards: 220, gauge: null, url: "https://www.knitpicks.com/delft-heather/p/25649", free: false, usedYarns: ["Knit Picks|Wool of the Andes Worsted"], sourceBrand: "Knit Picks" },
    { name: "Lyon Hat", image: "https://images4-g.ravelrycache.com/uploads/TheVelvetAcorn/978938720/DSC_3093_small2.jpg", designer: "The Velvet Acorn", craft: "knit", project: "Hat", weight: "Worsted", minYards: 110, maxYards: 220, gauge: null, url: "https://www.knitpicks.com/delft-heather/p/25649", free: false, usedYarns: ["Knit Picks|Wool of the Andes Worsted"], sourceBrand: "Knit Picks" },
    { name: "Bright Avenue Blanket", image: "https://images4-g.ravelrycache.com/uploads/KPStaff/1090535453/upload_thumbnail", designer: "Knit Picks", craft: "knit", project: "Blanket", weight: "Worsted", minYards: 1320, maxYards: 2640, gauge: null, url: "https://www.knitpicks.com/delft-heather/p/25649", free: true, usedYarns: ["Knit Picks|Wool of the Andes Worsted"], sourceBrand: "Knit Picks" },
    { name: "Carefree Comfort Blanket", designer: "Knit Picks", craft: "knit", project: "Blanket", weight: "Worsted", minYards: 1540, maxYards: 2640, gauge: null, url: "https://www.knitpicks.com/delft-heather/p/25649", free: false, usedYarns: ["Knit Picks|Wool of the Andes Worsted"], sourceBrand: "Knit Picks" },
    { name: "Tiergarten Pullover", designer: "Knit Picks", craft: "knit", project: "Sweater", weight: "Worsted", minYards: 880, maxYards: 1650, gauge: null, url: "https://www.knitpicks.com/delft-heather/p/25649", free: false, usedYarns: ["Knit Picks|Wool of the Andes Worsted"], sourceBrand: "Knit Picks" },
    { name: "Darby Pullover", designer: "Knit Picks", craft: "knit", project: "Sweater", weight: "Worsted", minYards: 880, maxYards: 1650, gauge: null, url: "https://www.knitpicks.com/delft-heather/p/25649", free: false, usedYarns: ["Knit Picks|Wool of the Andes Worsted"], sourceBrand: "Knit Picks" },
    { name: "Little Lakes Cardigan", image: "https://images4-f.ravelrycache.com/uploads/KPStaff/1039320131/upload_small2", designer: "Knit Picks", craft: "knit", project: "Sweater", weight: "Worsted", minYards: 880, maxYards: 1760, gauge: null, url: "https://www.knitpicks.com/delft-heather/p/25649", free: false, usedYarns: ["Knit Picks|Wool of the Andes Worsted"], sourceBrand: "Knit Picks" }
  ];
}());
